// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/bloodsteel/easynetes/internal/dao/host"
	"github.com/bloodsteel/easynetes/internal/dao/user"
	"github.com/bloodsteel/easynetes/internal/handler/api"
	"github.com/bloodsteel/easynetes/internal/handler/health"
	"github.com/bloodsteel/easynetes/pkg/config"
	"github.com/bloodsteel/easynetes/pkg/server"
)

// Injectors from wire.go:

// InitializeApplication 初始化app, 用来启动http server
func InitializeApplication(c *config.Config) (*server.Server, error) {
	db, err := provideDatabase(c)
	if err != nil {
		return nil, err
	}
	userDao := user.ProvideUserDao(db)
	hostInstanceDao := host.ProvideHostDao(db)
	apiServer := api.ProvideAPI(userDao, hostInstanceDao)
	healthServer := health.ProvideHealth()
	handler := ProvideRouter(apiServer, healthServer)
	serverServer := ProvideServer(handler, c)
	return serverServer, nil
}
